### ISSUE TITLE
It seems that the nested tag is not supported?

### ISSUE THREAD

**Issue by zhao414** [chrskerr/task-list-kanban#19]
I use tag like `#PL/C-重要`.
I can set the column as `PL/C-重要`, but the tag in the task is not recognized.
Moreover, when I drag a card into the column named `PL/C-重要`, I find a new tag is added to the task in its original file as `#plc-`.
Notice that: 
1. the letters are changed to the lower-case
2. `/` and other chinese charactors are removed.

**Comment by chrskerr** [comment]
I have pushed a fix for this, release 1.2.6, please let me know if it fixes things properly :)

**Comment by zhao414** [comment]
> I have pushed a fix for this, release 1.2.6, please let me know if it fixes things properly :)

Thank you for the quick reply.
I update the original comments to add some labels.

item 1 and 2 remain.

item 3, when I drag a card into the column named PL/C-重要, I find a new tag is added to the task in its original file as `#p-l-c-重要`, which should be '#PL/C-重要'（with upper-case letters and `/`）

item 4 remains.

item 5: Chinese is now OK, as shown above, but the `/` is missing
