### ISSUE TITLE
Automated tag addition breaks terminating blockids

### ISSUE THREAD

**Issue by Jeromandres** [chrskerr/task-list-kanban#4]
Obsidian allows linking to every block of text, the reference being "^" character followed by a sequence of letters

Today task-list-kanban adds the tag at the end of the task block, even if the task block is terminated by a block id
This can "permanently" break the link to the given task through the blockid

Could you change the way tags are added to add them before a potential blockid?

--------------------------
Background for my need:

1) I implemented a similar use case as task-list-kanban by in fact creating embedded links to tasks created elsewhere
2) I relied on some quick add triggers with backend javascript to select the priority in kanban and automatically adding the link to the right column in the kanban file
3) Migrating from my previous kanban set-up to your new plugin requires to have tag addition working correctly with blockids

**Comment by chrskerr** [comment]
To clarify, is it this syntax? https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note

To my understanding the serialisation should look like this.

- if the content ends with `/\^[a-zA-Z0-9-]+/` (also maybe trailing whitespace)
- then insert tags before this string

If that sounds right I can work on this shortly.

**Comment by Jeromandres** [comment]
Yes this is correct

no trailing spaces after the alphanumeric sequence, otherwise block link breaks
